# Generated by Django 5.2.4 on 2025-07-06 15:32

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField()),
                ('source_id', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding_vector', pgvector.django.vector.VectorField(verbose_name=1536)),
                ('model', models.TextField()),
                ('embedding_hash', models.CharField(max_length=64, unique=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents_1536',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='companynews',
            options={'default_related_name': 'company_news', 'managed': False},
        ),
    ]
